### ISSUE TITLE
STM32H743主机 USB枚举EC20有概率性会失败，控制器报告是DTERR，但是在USB总线上未观测到该错误

### ISSUE THREAD

**Issue by chengshuihang** [cherry-embedded/CherryUSB#118]
![image](https://github.com/cherry-embedded/CherryUSB/assets/45716763/c811569d-eda6-4665-a585-f2f865f842be)
![image](https://github.com/cherry-embedded/CherryUSB/assets/45716763/775d6a13-3576-4452-bd18-039379dfc098)
![image](https://github.com/cherry-embedded/CherryUSB/assets/45716763/df12b015-d789-450c-8058-dc78fb846080)
![image](https://github.com/cherry-embedded/CherryUSB/assets/45716763/a14c07fa-e787-4cf1-af45-f0032aabc16f)

**Comment by chengshuihang** [comment]
![image](https://github.com/cherry-embedded/CherryUSB/assets/45716763/0effbd9c-e509-4e41-90c8-e26998c3a7fb)
修改usb_hc_dwc2.c文件的两处位置，EC20可以稳定枚举。暂不清楚中断端点是否有影响

**Comment by sakumisu** [comment]
不允许注释

**Comment by sakumisu** [comment]
其次，你的分析仪太简陋了，自然分析不了这些错误，专业的分析仪是可以分析的

**Comment by sakumisu** [comment]
对于STM32H7 还有其他需要注意的点，没有看到你的移植相关的内容，不好分析，可以加入readme下的群，进群说
