### ISSUE TITLE
STM32F407 Problem

### ISSUE THREAD

**Issue by AndyW999** [cherry-embedded/CherryUSB#121]
I am using an STM32F407-Disco board using FS interface.
I have done all as described in https://cherryusb.readthedocs.io/zh_CN/latest/quick_start/stm32.html
I get the USB Serial Device enumerated in Win10 Device Manager but if I try to connect Putty to it I get 'Unable to open connection to COM3' 'Unable to configure serial port'

The STM32CubeIDE project is in Dropbox -

https://www.dropbox.com/scl/fo/ofwl3x4rvzbg2nj2xnqdy/h?rlkey=gdpsh40vuqq322hcixo89xakv&dl=0

Thanks

Andy.

**Comment by sakumisu** [comment]
It is not usb issue i think, please refer to my stm32 demo, and confirm your board is ok.

**Comment by AndyW999** [comment]
I know ;)

I just copied it all.

**Comment by AndyW999** [comment]
If I use the normal STM32CubeIDE ioc set up and use their middleware to set it to CDC it works and I can connect Putty.

So the board is OK.

I am using the cdc_acm_template.c file from your demo directory.

Viewing the USB status using USBDeview it shows ST Class 02, Protocol 01 with Cherry Class 00 Protocol 00. 

Please see attached files.

But as it is using your files I have no idea why.

![CherryUSB - USBDeview](https://github.com/cherry-embedded/CherryUSB/assets/5624292/bae25905-63a4-4184-a738-8727892d0bd9)
![STUSB - USBDeview](https://github.com/cherry-embedded/CherryUSB/assets/5624292/43c895c7-a457-44cc-90c6-44d58bf641f3)

**Comment by sakumisu** [comment]
Please implment your printf, thanks, you do not implment this and COM3 is not cherryusb port.

**Comment by sakumisu** [comment]
Others i cannot help you, try by yourself, or use my demo.

**Comment by sakumisu** [comment]
https://github.com/CherryUSB/cherryusb_stm32

**Comment by sakumisu** [comment]
If you do not implment printf, please do not use cherryusb

**Comment by AndyW999** [comment]
I have implemented printf and here are the results -

[I/USB] ========== dwc2 udc params ==========
[I/USB] CID:00001200
[I/USB] GSNPSID:4f54281a
[I/USB] GHWCFG1:00000000
[I/USB] GHWCFG2:229dcd20
[I/USB] GHWCFG3:020001e8
[I/USB] GHWCFG4:0ff08030
[I/USB] dwc2 fsphy type:1, hsphy type:0, dma support:0
[I/USB] dwc2 has 4 endpoints, default config: 4 endpoints
[I/USB] =================================
[W/USB] Ignore DQD in fs
[I/USB] Open ep:0x83 type:3 mps:8
[I/USB] Open ep:0x02 type:2 mps:64
[I/USB] Open ep:0x81 type:2 mps:64

**Comment by sakumisu** [comment]
It works ok, but why serial port doesnot work, i dont know, sorry.

**Comment by AndyW999** [comment]
If you have the time and patience to work with me I would like to solve this.

My goal is to eventually get RNDIS host working to interface with the DMR radios we use.

I still think the problem is related to the earlier views I sent from USBDeview  where the class and protocol are shown as 00

**Comment by sakumisu** [comment]
If it is class and protocol issue, do you think this issue can  exist 2 years?

**Comment by sakumisu** [comment]
Please use my demo, thanks ,others i cannot help you.

**Comment by AndyW999** [comment]
I am using the code from your demo and following the instructions you give to do it.

I had to generate my own project as I do not have an STM32f469 board, only an STM32F407 board.

I have set up a Win7 32 bit VM and it will not even load a driver.

I tried a ‘clean’ Win10 VM and it took a while to get a Com port number but Putty kept timing out.

I have re-uploaded the STM32CubeIDE zipped archive project to the same Dropbox as before –

https://www.dropbox.com/scl/fo/ofwl3x4rvzbg2nj2xnqdy/h?rlkey=gdpsh40vuqq322hcixo89xakv&dl=0

**Comment by sakumisu** [comment]
Solve it byyourself.

**Comment by sakumisu** [comment]
Are you a chinese? You can join the qq group to talk with it.

**Comment by AndyW999** [comment]
I have now tried NUCLEO -F429ZI board using FS and it is the same.

Please could you tell me which drivers are used in Windows 10?

Mine uses 
C:|WINDOWS\system32\DRIVERS\usbser.sys 
and I do not know if this is correct.

**Comment by sakumisu** [comment]
And my class code is 02  02  01, not 00 00 00,thanks

**Comment by sakumisu** [comment]
Nothing problem, sir, use USBDeview v3.06
![image](https://github.com/cherry-embedded/CherryUSB/assets/46106817/cbf7dc81-9077-4bbb-86d7-28356fe7630c)

**Comment by sakumisu** [comment]
![image](https://github.com/cherry-embedded/CherryUSB/assets/46106817/fbf181e9-b332-4c0c-8db2-ba4382ae7a57)

**Comment by sakumisu** [comment]
![image](https://github.com/cherry-embedded/CherryUSB/assets/46106817/96df2f19-c388-438c-8ff8-b636cc02fb0c)

**Comment by sakumisu** [comment]
![image](https://github.com/cherry-embedded/CherryUSB/assets/46106817/52b20690-c33d-4a88-831b-82256b9c74d2)

**Comment by sakumisu** [comment]
Nothing problem, sir, use USBDeview v3.06

**Comment by sakumisu** [comment]
And for stm32, they have their own windows driver, you can use other class like hid or msc. I doo not want to answer for this, it is an invalid time.

**Comment by AndyW999** [comment]
Thanks for the screenshots!

This is really strange, I updated USBDview to 3.06, screenshot attached.

I did a driver update and put usbser.inf in it's own directory and told it to use it but it continues to use usb.inf.

Why do things like this always happen to me ;)

I have tried - 
STM32F407Disco with FS and HS
Nucleo STM32F429ZIT6 with FS

I do not know what to do as my other Windows PC's do the same.

Thanks for helping me, I do appreciate it ;)


![Screenshot (258)](https://github.com/cherry-embedded/CherryUSB/assets/5624292/465a786d-2320-48b1-9a37-a30cd89a8e9f)

**Comment by AndyW999** [comment]
Is it possible for you to send me an STM32F407 working demo?

**Comment by AndyW999** [comment]
And this is the output from UVCview.

[UVCView-CherryUSB_CDC.txt](https://github.com/cherry-embedded/CherryUSB/files/12180939/UVCView-CherryUSB_CDC.txt)

**Comment by sakumisu** [comment]
And you do not use USBDview correctly, you should select COMX and device name is a serie number.

**Comment by sakumisu** [comment]
You driver letter is null but mine is COM58.

**Comment by sakumisu** [comment]
That's all, please check by yourself, if you think my descriptor is incorrect, you can copy st descriptor

**Comment by sakumisu** [comment]
OK, i know, you can change your vid and pid to other, not ffff, you can modfiy with 0xabcd

**Comment by sakumisu** [comment]
Last, you should solve by yourself, you can use other pc with windows or linux to have a try, or stop using cherryusb.

**Comment by sakumisu** [comment]
It wastes me too much time.

**Comment by AndyW999** [comment]
I know!

I have some STM32F103 boards soon, I will try it with them.

I know CherryUSB works but I wish it would for me.

Can you let me have a working set of source code that use have tried or even HEX code to program my STM32F407 board with?

I am sorry for wasting your time.

**Comment by sakumisu** [comment]
how about testing other class like msc or hid？dwc driver is ok i think, maybe some others like windows drivers have confused

**Comment by AndyW999** [comment]
Windows confused? However could that happen ;)

Yes, trying other classes was next for me to try but I will try not to bother you…

I will wait until I get the F103 boards so I can try the fsdev driver instead.
