### ISSUE TITLE
Is there any example of UVC video capture?

### ISSUE THREAD

**Issue by 0x0fe** [cherry-embedded/CherryUSB#145]
Just wondering if there is any example of standard UVC video capture in USB HOST mode.

**Comment by sakumisu** [comment]
Enterprise customization， not opensource.

**Comment by sakumisu** [comment]
Iso driver for video is not opensource, but there is a template for parsing video packet(if you can write iso driver), https://github.com/cherry-embedded/CherryUSB/blob/master/demo/usb_host.c

**Comment by 0x0fe** [comment]
ok please add my qq 3265649676
