### ISSUE TITLE
MSC Writing very slow disk

### ISSUE THREAD

**Issue by WGR7** [cherry-embedded/CherryUSB#151]
Hi,

I have a very slow media that needs much millisecs to write to disk.

What value should **usbd_msc_sector_write** return if the writing to disk has not completed yet?
If Cherry can delay host to write new data while **usbd_msc_sector_write** is waiting media complete. How could I know if host is asking a write status or sending new data if **usbd_msc_sector_write** was called again by usb interrupt while write is in progress?

Regards.

**Comment by sakumisu** [comment]
Hi, will return -ETIMEOUT, default is 5s.

**Comment by WGR7** [comment]
So, my function body should be like this?


```
int usbd_msc_sector_write(uint32_t sector, uint8_t *buffer, uint32_t length)
{

    if(GetDiskStatus() == WRITE_IN_PROGRESS){
          return -ETIMEOUT;
     }else{

    disk_write(buffer, sector, length);
    return 0;
    }

}
```

**Comment by WGR7** [comment]
Thanks.
