### ISSUE TITLE
使用musb_dc, cdc_acm_demo时，当发送数据长度大于等于CDC_MAX_MPS时，主机无法打开设备或需要等很长时间才能打开设备

### ISSUE THREAD

**Issue by saisesai** [cherry-embedded/CherryUSB#152]
CherryUSB版本: Release v0.10.2 c143554
芯片：AIR105/MH1903S-QFN88
相同的demo代码在STM32F103和CH32V203均可正常工作
[项目完整代码](https://saiacg.lanzoub.com/iYPxm1fxjcja)

**Comment by sakumisu** [comment]
这个没听说过，可能芯片 ip有问题，建议参考其他相同ip芯片，多谢。
