### ISSUE TITLE
Please provide a Bouffalo SDK host example

### ISSUE THREAD

**Issue by harbaum** [cherry-embedded/CherryUSB#165]
The cherryusb inside the bouffalo sdk is still 0.10.0. I have been able to manually update to 0.10.2 but the latest version 1.0.0 doesn't implement easily into the bouffalo SDK, anymore.

Please provide an example for USB (host) usage of the latest cherryusb 1.0.0 with the bouffalo SDK. Or even better, please update the bouffalo SDK with the latest cherryusb.

**Comment by sakumisu** [comment]
Sorry, not updatevany more

**Comment by sakumisu** [comment]
You can update by yourself with guide.

**Comment by harbaum** [comment]
I don't understand. The bouffalo SDK will not be updated, anymore? Or only the USB inside the bouffalo SDK? 

What do you mean by guide? I tried updating. Main changes are:

- removing `usbd_ep_open()` from `bflb_usb_v2.c` 
- pointing to `extern struct usb_setup_packet g_setup_buffer[];`  in `bflb_usb_v2.c `
- and replaced` usbh_initialize() ` by  `usbh_initialize(usbh_alloc_bus(0, BLFB_USB_BASE))`

I had to do some minor other changes in my code. But I had already done this for 0.10.2 and that was still working

This is now crashing once I plug a USB device with:

```
init usbh class
exception_entry
mcause=30000004
mepc:a00064d8
mtval:0000002d
Load address misaligned

-+-+-+- BFLB COREDUMP v0.0.1 +-+-+-+
...
```

**Comment by sakumisu** [comment]
Follow this guide: https://cherryusb.readthedocs.io/zh-cn/latest/quick_start/other_chip.html, I think you have wrong in porting with cherryusb master, so please use v0.10.2

**Comment by sakumisu** [comment]
From your code, you have many mistakes
- do not remove usbd_ep_open()
- pointing to extern struct usb_setup_packet g_setup_buffer[]; in bflb_usb_v2.c  what is this?
- and replacedusbh_initialize() by usbh_initialize(usbh_alloc_bus(0, BLFB_USB_BASE)), only this cannot work.

**Comment by sakumisu** [comment]
For host, where is your irq??? please refer to https://github.com/CherryUSB/cherryusb_stm32/blob/5727f65f5a3da97698b2581cc3055258a57ed182/usb_host/stm32f429igt6/Core/Src/stm32f4xx_it.c#L216

**Comment by sakumisu** [comment]
And ehci offset you muse set.

**Comment by sakumisu** [comment]
So, following above, please use v0.10.2 if you have no ability to proting with master.

**Comment by sakumisu** [comment]
Or you can use v1.0.0, its api is the same with v0.10.2, master is for multi port.

**Comment by sakumisu** [comment]
For device, please refer to this commit : https://github.com/cherry-embedded/CherryUSB/commit/29d45ef5c7547b75a347e992fc4198f03da31f15

**Comment by sakumisu** [comment]
Follow this #166

**Comment by harbaum** [comment]
Yes,  usbd_ep_open() needs to be present. The fact that it compiles without it means that all invocations of this functions are optimized away which in turn means that some quite important call is missing somewhere when doing this naived simple way of just replacing the old components/usb/cherryusb with the updated one.

It's rather strange to hear that support for the bouffalo line of MCUs has ended so early. Why is that?

**Comment by harbaum** [comment]
> Follow this #166

Thanks! This was the info I was missing. USB host compiles now and seems to run.

**Comment by sakumisu** [comment]
Hello, do you have solved this？For detail, you can check with following patches.

- change `const struct usbd_endpoint_cfg *ep_cfg` to `const struct usb_endpoint_descriptor *ep` or revert change.
- Follow #166  and modify with `bflb_irq_attach(37, USBH_IRQ, NULL);` in bflb_usb_v2.c

**Comment by harbaum** [comment]
Yes, I have integrated cherryusb 1.0.0 into the bouffalo sdk. I have also added a host driver for the Xbox controller and compatible devices. See http://GitHub.com/Harbaum/bouffalo_sdk

This is being used in the MiSTeryNano FPGA: http://GitHub.com/Harbaum/MiSTeryNano

**Comment by sakumisu** [comment]
> Yes, I have integrated cherryusb 1.0.0 into the bouffalo sdk. I have also added a host driver for the Xbox controller and compatible devices. See http://GitHub.com/Harbaum/bouffalo_sdk
> 
> This is being used in the MiSTeryNano FPGA: http://GitHub.com/Harbaum/MiSTeryNano

That's cool, sir, i will be continuous concerned with your project.
