### ISSUE TITLE
关于USB HID设备与电脑通讯的方式

### ISSUE THREAD

**Issue by AnemosCiel** [cherry-embedded/CherryUSB#167]
大佬，最近有个需求，USB Deice实现键盘和鼠标复合设备，同时还需要和电脑通讯，那么通讯方式可以选择HID键盘的IN端点吗？还是需要再复合一个HID自定义设备？还是再复合CDC设备？
    求大佬解惑！另外，cherry usb现在有多复合设备的例程么？

**Comment by sakumisu** [comment]
demo 底下一堆复合例程
