### ISSUE TITLE
1 RNDIS + 3 CDC Endpoints example demo

### ISSUE THREAD

**Issue by sidd-kishan** [cherry-embedded/CherryUSB#168]
I am developing a Pi PICO W based RNDIS USB WiFi dongle for windows on ARM platform.
I have needed an example with RNDIS and multiple serial EPs.

RNDIS - For internet
CDC EP2 - SSID SCAN
CDC EP3 - Credential management
CDC EP4 - MISC

I have created a template example : [sidd-kishan/pico-examples-cherryusb](https://github.com/sidd-kishan/pico-examples-cherryusb/blob/3018e100751c1b2f9336846268f886f42bb9e95a/cherryusb/device/rndis_http_server/src/cdc_rndis_device.c)

Please let me know if the same can be supported as a formal demo example

**Comment by sakumisu** [comment]
You should confirm if rp2040 has so much endpoints

**Comment by sakumisu** [comment]
Your code is right if it supports these endpoints.

**Comment by sidd-kishan** [comment]
Hi Team,
              PFB the screenshot from the latest build from my project [sidd-kishan/pico-examples-cherryusb](https://github.com/sidd-kishan/pico-examples-cherryusb) Please let me know if it is sufficient as an evidence:-

<img width="953" alt="image" src="https://github.com/cherry-embedded/CherryUSB/assets/1007208/8eb07f32-2d38-4c72-b5c8-f1f76ea08cf9">

**Comment by sakumisu** [comment]
It works ok.

**Comment by sidd-kishan** [comment]
Updated the code now all 3 endpoints working as [independent loopback](https://github.com/sidd-kishan/pico-examples-cherryusb/blob/master/cherryusb/device/rndis_http_server/src/cdc_rndis_device.c)
