### ISSUE TITLE
字符串描述符修改很不方便

### ISSUE THREAD

**Issue by tyustli** [cherry-embedded/CherryUSB#202]
字符串描述符修改很不方便，每次只能挨个检查，是否考虑用宏定义一个字符串？协议栈里面去处理。

**Comment by sakumisu** [comment]
你可以使用 CONFIG_USBDEV_ADVANCE_DESC模式，去修改字符串

**Comment by sakumisu** [comment]
你的这个需求，只能在开启上面这个宏以后才能加了，扫描模式的这种是没法加的

**Comment by tyustli** [comment]
![image](https://github.com/cherry-embedded/CherryUSB/assets/43946994/f3effab9-f6ba-49a3-a828-1e89d782f396)

CONFIG_USBDEV_ADVANCE_DESC 模式开启之后，字符串还是需要挨个修改
```c
#define PRODUCT_STRING  "Cherryusb cdc demo"
```

感觉能实现上面这种最好

**Comment by tyustli** [comment]
我的代码好改，只是使用过程中感觉这里不友好，看你后续是不是可以考虑用这种方式

**Comment by sakumisu** [comment]
没问题

**Comment by sakumisu** [comment]
已修改

**Comment by sakumisu** [comment]
> CONFIG_USBDEV_ADVANCE_DESC

开启 CONFIG_USBDEV_ADVANCE_DESC 宏，使用新的注册方式，旧版本注册方式不做支持

**Comment by sakumisu** [comment]
参考 https://github.com/cherry-embedded/CherryUSB/blob/master/demo/cdc_acm_msc_template.c
