### ISSUE TITLE
STM32H7实现CDC例程接收遇到的问题

### ISSUE THREAD

**Issue by Home-Laozang** [cherry-embedded/CherryUSB#216]
大佬你好，我在使用STM32H743上使用这个CDC例程时，电脑端测试软件是SSCOM，SSCOM接收板卡发过来的2K数据是正常的。但是SSCOM往板卡发送的数据，如果我勾选“加回车换行”，板卡端就好想没有接收到一样，需要累计到2K数据量才调用接收回调函数。

但是不勾选“加回车换行”，板卡端就能正常接收数据，并且在回调里面打印接收的数据量。

**Comment by sakumisu** [comment]
很合理，没有问题，自己参考文档，中断完成条件。

**Comment by sakumisu** [comment]
跟你什么回车换行没有任何关系，说明你勾选回车换行以后，长度是64的倍数，usb协议要求最后一个包是小于ep mps

**Comment by Home-Laozang** [comment]
巧了，确实是64个字节。大佬牛逼。多谢多谢。我用USBX，动不动就超过100K Flash的占用量，效率且不说，Flash比较少的芯片还没法搞。这个协议栈太棒了，果然小而美。膜拜

**Comment by sakumisu** [comment]
点点star，加加群啊，readme底下

**Comment by Home-Laozang** [comment]
已点，已加
