### ISSUE TITLE
 uint8_t class; in CherryUSB conflict with reserved keyword c++

### ISSUE THREAD

**Issue by obitvn** [cherry-embedded/CherryUSB#220]
![image](https://github.com/cherry-embedded/CherryUSB/assets/43460353/9666e217-ca42-4dd9-93ba-c9e390469124)
Hi, I am trying to use cherryUSB on ESP32 with C++. I had it running on previous versions, but in the current version, the usbh_class_info structure in usbh_core.h contains the keyword class, causing a conflict with C++.
![image](https://github.com/cherry-embedded/CherryUSB/assets/43460353/6b11dae5-79b2-4ca0-8457-eabf47293cb6)
So we should consider changing class to another keyword (I have seen this issue since 2022, in issues #8 , but it seems it has not been completely fixed)?

**Comment by obitvn** [comment]
I'm also trying to find a solution that doesn't modify the CherryUSB source code, but it seems extern "C" { } doesn't help.

**Comment by sakumisu** [comment]
This #8 is fixed for device and no host stack at that time, i will consider to fix this in next release.

**Comment by sakumisu** [comment]
You can follow this demo https://github.com/CherryUSB/cherryusb_esp32/tree/latest, and do not include usbh_core.h in c++ source file.

**Comment by obitvn** [comment]
Thank you, this works.
