### ISSUE TITLE
Version in project specific file?

### ISSUE THREAD

**Issue by harbaum** [cherry-embedded/CherryUSB#226]
What's the idea behind putting the version and version string into the usb_config.h ? 

These are imho to be handled in the projects and thus won't reflect the state of cherryusb.

Can the version please be moved into the charryusb main files? I can then do things like `#if CHERRYUSB_VERSION > 0x010300` and the like.

**Comment by sakumisu** [comment]
You can include xxx_core.h and it inculdes usb_config.h. The reason why version is in usb_config is that anyone who wants to ask some questions and they do not use git, they should provide version and then i can know the changes, this version in usb_config is readonly.

**Comment by harbaum** [comment]
Yes. But a project like mine comes with it's own project specific usb_config.h and that won't necessarily match the cherryusb stack. E.g. here: https://github.com/harbaum/FPGA-Companion/blob/main/src/bl616/usb_config.h

**Comment by harbaum** [comment]
Ok, will do that.

**Comment by sakumisu** [comment]
Moved macros into usb_version.h
