### ISSUE TITLE
[dwc2][dc]dwc2_set_mode是否需要添加延时确保生效?

### ISSUE THREAD

**Issue by wdfk-prog** [cherry-embedded/CherryUSB#237]
https://github.com/cherry-embedded/CherryUSB/blob/70944027c50375cda040587980fa2e92e985f536/port/dwc2/usb_dc_dwc2.c#L170-L179

- 观察STM32H7手册发现OTG_GUSBCFG->FDMOD的描述发现`将强制位置 1 后，应用程序必须等待至少 25 ms 后更改方可生效。`
![image](https://github.com/user-attachments/assets/27f032b5-c466-4a33-8f29-4ed07809456d)

- 观察STM32驱动代码也是如此
https://github.com/STMicroelectronics/stm32h7xx_hal_driver/blob/b2b4c45001f1b6b72ae449713607896fd6ca4c6b/Src/stm32h7xx_ll_usb.c#L244-L290

**Comment by sakumisu** [comment]
应该是需要的

**Comment by wdfk-prog** [comment]
https://github.com/cherry-embedded/CherryUSB/blob/70944027c50375cda040587980fa2e92e985f536/port/dwc2/usb_dc_dwc2.c#L181-L194

- 这里也少了等待条件
![image](https://github.com/user-attachments/assets/2aecd751-de1d-40b8-8af5-43cf520364c0)

https://github.com/STMicroelectronics/stm32h7xx_hal_driver/blob/b2b4c45001f1b6b72ae449713607896fd6ca4c6b/Src/stm32h7xx_ll_usb.c#L484-L519

**Comment by sakumisu** [comment]
https://github.com/CherryUSB/cherryusb_stm32/blob/master/usb_device/stm32f429igt6/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c 并没有。请参考 dwc2 官方手册，不要信这些非官方代码

**Comment by sakumisu** [comment]
目前这些没有实际影响，所以暂不考虑，只认可 DWC2 官方手册

**Comment by sakumisu** [comment]
再给几个参考都是没有的 https://github.com/STMicroelectronics/stm32h7xx_hal_driver/blob/v1.6.0/Src/stm32h7xx_ll_usb.c

**Comment by sakumisu** [comment]
ST 自己都不知道要不要加呢

**Comment by sakumisu** [comment]
大佬可以加readme 底下qq群，聊聊

**Comment by wdfk-prog** [comment]
> 大佬可以加readme 底下qq群，聊聊

\(^o^)/~好

**Comment by wdfk-prog** [comment]
> 目前这些没有实际影响，所以暂不考虑，只认可 DWC2 官方手册

![image](https://github.com/user-attachments/assets/c7afa520-4ec7-408b-9d2f-722391ba9dba)

- DWC2手册里面是有说要的,觉得最好得补上;
- 能成功的自然不会说有问题,失败的也不一定知道是什么地方出了问题

**Comment by sakumisu** [comment]
> > 目前这些没有实际影响，所以暂不考虑，只认可 DWC2 官方手册
> 
> ![image](https://private-user-images.githubusercontent.com/66928464/357339138-c7afa520-4ec7-408b-9d2f-722391ba9dba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MzkzMjEsIm5iZiI6MTcyMzUzOTAyMSwicGF0aCI6Ii82NjkyODQ2NC8zNTczMzkxMzgtYzdhZmE1MjAtNGVjNy00MDhiLTlkMmYtNzIyMzkxYmE5ZGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA4NTAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZWQwZjIyZjdlODNjOTc5YzA2MTFiMTRmMzllOGIzNmJiMGRmYmVmZjllNDE0OGYyMjZkZWI3NTNmZjc3YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O3gnhquDS7Lc4hmdT66koh96S6SUHsYdlH6ZFVKB6c0)
> 
> * DWC2手册里面是有说要的,觉得最好得补上;
> * 能成功的自然不会说有问题,失败的也不一定知道是什么地方出了问题

小改动没什么没问题，可以加上

**Comment by sakumisu** [comment]
已更新
