### ISSUE TITLE
主机模式下，USB的缓存是否可以支持动态分配

### ISSUE THREAD

**Issue by qqjmk15263** [cherry-embedded/CherryUSB#243]
使用STM32F407运行主机模式，直接外接HUB，在之前旧的版本中，单片机的内存占用不大，更新版本之后，USB的大部分缓存都直接通过全局变量提前分配好，这样在没有接入任何USB设备时也占用了大量的内存，对于小内存的单片机设备不友好，是否可以提供一个编译选项，运行内存进行动态分配

**Comment by sakumisu** [comment]
修改 usb_config 中相关宏的个数即可

**Comment by sakumisu** [comment]
这些内存是需要指定相关的section的，对ram的 cache属性有要求，所以不会做动态内存

**Comment by sakumisu** [comment]
默认配置的个数比较多，配置少的话会带来用户在插入多个设备或者多个功能的时候报错（也就2K ~ 4K 左右，其实也不大）

**Comment by qqjmk15263** [comment]
> 默认配置的个数比较多，配置少的话会带来用户在插入多个设备或者多个功能的时候报错（也就2K ~ 4K 左右，其实也不大）

好的

**Comment by sakumisu** [comment]
对了还有个原因，考虑到安全性，不允许用动态内存

**Comment by qqjmk15263** [comment]
> 对了还有个原因，考虑到安全性，不允许用动态内存

我是自己添加一个宏定义，可以切换内存为动态分配，主要是我使用的stm32片上内存太少，如果缓存开太大，编译器预分配的ram过多，可能导致超过芯片内存而无法编译成功，因此我将用到的大缓存整块分配到外部SRAM上，目前来看，运行还是稳定的
