### ISSUE TITLE
Any plans for RP2350 support?

### ISSUE THREAD

**Issue by matsobdev** [cherry-embedded/CherryUSB#255]
Same as title.

**Comment by sakumisu** [comment]
Sorry, no plan for rp series, you can use tinyusb instead.

**Comment by matsobdev** [comment]
Actually it is working with RP2350. Just required registers configuration change - pulling from SDK for RP2350. Interrupts was mandatory as well.

**Comment by sidd-kishan** [comment]
@matsobdev Please share your changes I can port it to the latest version

**Comment by matsobdev** [comment]
Tested with SDK 1.5.1 and 2.1.0. I guess it might work with latest release right of the bat, but tried first with safe bet.
[RP2350_changes.zip](https://github.com/user-attachments/files/18390271/RP2350_changes.zip)

**Comment by sakumisu** [comment]
> Tested with SDK 1.5.1 and 2.1.0. I guess it might work with latest release right of the bat, but tried first with safe bet. [RP2350_changes.zip](https://github.com/user-attachments/files/18390271/RP2350_changes.zip)
> 
> PS. ARM is working, RISCV is not. If I did `__riscv` definition right, there is still something more to it. PS2. It works as well with 1.4.2 version of CherryUSB (and not with RISCV xD): [RP2350_changes_1.4.2.zip](https://github.com/user-attachments/files/18413917/RP2350_changes_1.4.2.zip). Then `busid` is hardcoded 0, for example:
> 
> ```
> usbd_ep_start_write(0, HID_INT_EP, raport, 6);
> ```
> 
> and `reg_base` - `USBCTRL_REGS_BASE` from Pico SDK:
> 
> ```
> hid_keyboard_init(0, USBCTRL_REGS_BASE);
> ```
> 
> PS3. I'm not sure about `USBCTRL_REGS_BASE` - other garbage works as well.

Thanks, pico official contacts with me and we will restart pico support now.

**Comment by sakumisu** [comment]
> [@matsobdev](https://github.com/matsobdev) Please share your changes I can port it to the latest version

Thank you also.

**Comment by matsobdev** [comment]
Good news to hear that. I saw some movements in https://github.com/raspberrypi/pico-sdk/issues/1057.
