### ISSUE TITLE
1.4.1版本 bl616/bl618 无法使用 msc

### ISSUE THREAD

**Issue by Dozingfiretruck** [cherry-embedded/CherryUSB#270]
### 描述一下这个bug / Describe the bug

我想使用msc，提示需要格式化，点击格式化会失败
cdc功能验证正常

### 复现步骤 / To Reproduce

最新1.4.1使用 msc_ram_template.c做测试

### 设备信息 / Target Device

bl618

### 日志 / Log

无异常日志输出

### 商业 / Business

- [ ] 是 / Yes

**Comment by sakumisu** [comment]
测试没有问题，建议再自己研究下。使用我们官方 demo 下的template

**Comment by Dozingfiretruck** [comment]
> 测试没有问题，建议再自己研究下。使用我们官方 demo 下的template

你好，官方demo下的我也测试了是一样的，

https://github.com/Dozingfiretruck/bouffalo_sdk

这是我的代码，bouffalo部分是直接拉的子模块，跑 usbd_msc_ram 就能复现

**Comment by sakumisu** [comment]
https://github.com/cherry-embedded/CherryUSB/blob/master/demo/msc_ram_template.c 这才是我们官方，请注意

**Comment by Dozingfiretruck** [comment]
> https://github.com/cherry-embedded/CherryUSB/blob/master/demo/msc_ram_template.c 这才是我们官方，请注意

这个我刚才跑了，是一样的效果，和上面发的是一样的效果，都是格式化失败

**Comment by sakumisu** [comment]
那就不知道了，自己解决把

**Comment by Dozingfiretruck** [comment]
> 那就不知道了，自己解决把

你这边测试正常的是么？那我再看看，我这测试1.0.0是正常的

**Comment by sakumisu** [comment]
撤到1.4再看看呢

**Comment by Dozingfiretruck** [comment]
> 撤到1.4再看看呢

今天撤到过1.4.0测试，情况一样，也是格式化失败，但是cdc功能都是正常的，之后没有继续回退

**Comment by sakumisu** [comment]
那就没办法了，应该是你移植问题了。参考 https://github.com/hpmicro/hpm_sdk/tree/main/middleware/cherryusb

**Comment by Dozingfiretruck** [comment]
> 那就没办法了，应该是你移植问题了。参考 https://github.com/hpmicro/hpm_sdk/tree/main/middleware/cherryusb

实际上移植文件我直接用的官方的 https://github.com/cherry-embedded/CherryUSB/blob/master/port/bouffalolab/usb_dc_bl.c 没有改动任何代码，我再看下是否有问题，谢谢

**Comment by sakumisu** [comment]
下载这个测试下 [cherryusb_bl616.zip](https://github.com/user-attachments/files/17570053/cherryusb_bl616.zip)

**Comment by Dozingfiretruck** [comment]
> 下载这个测试下 [cherryusb_bl616.zip](https://github.com/user-attachments/files/17570053/cherryusb_bl616.zip)，终端输入 msc

![image](https://github.com/user-attachments/assets/49068351-b19b-4d60-abdb-05aabeaf5ee7)
好像这个命令没注册？

**Comment by sakumisu** [comment]
[cherryusb_bl616.zip](https://github.com/user-attachments/files/17570234/cherryusb_bl616.zip)

**Comment by sakumisu** [comment]
还有问题的话，加群把

**Comment by Dozingfiretruck** [comment]
> [cherryusb_bl616.zip](https://github.com/user-attachments/files/17570234/cherryusb_bl616.zip)

这个能正常格式化

**Comment by sakumisu** [comment]
那就检查移植问题把

**Comment by Dozingfiretruck** [comment]
> 那就检查移植问题把

OK。非常感谢

**Comment by sakumisu** [comment]
![image](https://github.com/user-attachments/assets/eede1cbf-00c8-4177-b0ec-a26b3787a538)

**Comment by sakumisu** [comment]
[usb_config.zip](https://github.com/user-attachments/files/17570365/usb_config.zip)

**Comment by sakumisu** [comment]
![image](https://github.com/user-attachments/assets/adda416a-865f-465d-ab97-ffae0d3c6043)

**Comment by Dozingfiretruck** [comment]
> [usb_config.zip](https://github.com/user-attachments/files/17570365/usb_config.zip)

问题找到了，我没有在usb_config.h 中定义 CONFIG_USB_HS ，但是这个是sdk默认定义的。。。 
![image](https://github.com/user-attachments/assets/2847cbcb-ff5e-437a-9c22-794eb3b7d04a)

**Comment by sakumisu** [comment]
有没有一种可能，本来人家sdk里cmake里是有的，现在你用了我这边的cmake。他没了

**Comment by Dozingfiretruck** [comment]
> 有没有一种可能，本来人家sdk里cmake里是有的，现在你用了我这边的cmake。他没了

是这样的，sdk中定义的CONFIG_USB_HS传给cmake，原版sdk中在cherryusb中是自己sdk写的cmake编译的，其中加了这个宏，哈哈哈，问题解决了，感谢感谢
