### ISSUE TITLE
连接usbhub枚举失败

### ISSUE THREAD

**Issue by zll900720** [cherry-embedded/CherryUSB#278]
### 描述一下这个bug / Describe the bug

我使用 https://github.com/CherryUSB/cherryusb_stm32 的例程(f103c8)未做任何修改 直接连接在电脑的usb口测试ok,但是通过usbhub连接是枚举失败,我更换了一个usbhub问题一样

### 复现步骤 / To Reproduce

首先连接usbhub再连上单片机

### 设备信息 / Target Device

stm32f103c8t6  fsdev

### 日志 / Log

[0m[D/USB] EP0 send 18 bytes, 0 remained
[0m[0m[D/USB] EP0 recv out status
[0m[0m[D/USB] EP0 send 0 bytes, 0 remained
[0m[0m[D/USB] EP0 send 18 bytes, 0 remained
[0m[0m[D/USB] EP0 recv out status
[0m[0m[D/USB] EP0 send 64 bytes, 11 remained
[0m[0m[D/USB] EP0 send 11 bytes, 0 remained
[0m[0m[D/USB] EP0 recv out status
[0m[0m[D/USB] EP0 send 18 bytes, 0 remained
[0m[0m[D/USB] EP0 recv out status
[0m[0m[D/USB] EP0 send 18 bytes, 0 remained
[0m[0m[D/USB] EP0 recv out status
[0m[0m[D/USB] EP0 send 0 bytes, 0 remained
[0m[0m[D/USB] EP0 send 18 bytes, 0 remained
[0m[0m[D/USB] EP0 recv out status
[0m[0m[D/USB] EP0 send 18 bytes, 0 remained
[0m[0m[D/USB] EP0 recv out status
[0m[0m[D/USB] EP0 send 18 bytes, 0 remained
[0m[0m[D/USB] EP0 recv out status
[0m[0m[D/USB] EP0 send 0 bytes, 0 remained
[0m[0m[D/USB] EP0 send 18 bytes, 0 remained
[0m[0m[D/USB] EP0 recv out status
[0m[0m[D/USB] EP0 send 18 bytes, 0 remained
[0m[0m[D/USB] EP0 recv out status
[0m[0m[D/USB] EP0 send 18 bytes, 0 remained
[0m[0m[D/USB] EP0 recv out status
[0m[0m[D/USB] EP0 send 0 bytes, 0 remained
[0m[0m[D/USB] EP0 send 18 bytes, 0 remained
[0m[0m[D/USB] EP0 recv out status
[0m

Bus Hound 6.00 capture on Windows Vista (x64). Complements of www.perisoft.net

  Device - Device ID (followed by the endpoint for USB devices)
            (62) PCAN-USB
            (72) USB Composite Device
            (73) USB Composite Device
  Length - Total transfer length
  Phase  - Phase Type
            CTL   USB control transfer       RESET bus reset
            IN    Data in transfer           USTS  USB status
            NTSTS NTSTATUS value             ok    command complete
  Data   - Hex dump of the data transferred
  Descr  - Description of the phase
  Cmd... - Position in the captured data
  Driver - Driver that submitted the command
            ntoskrnl     : NT Kernel & System 10.0.22621.4455 (WinBuild.160101.0800)
            usbccgp      : USB Common Class Generic Parent Driver 10.0.22621.4391 (WinBuild.160101.0800)

Device  Length    Phase  Data                                                Description       Cmd.Phase.Ofs(rep)  Driver      
------  --------  -----  --------------------------------------------------  ----------------  ------------------  ------------
  73.0            CTL    80 06 00 01  00 00 12 00                            GET DESCRIPTOR           1.1.0        ntoskrnl      
  73.0        18  IN     12 01 00 02  ef 02 01 40  83 04 f1 ff  00 01 01 02  .......@........         1.2.0                      
                         03 01                                               ..                       1.2.16                     
  73.0            CTL    80 06 00 02  00 00 09 00                            GET DESCRIPTOR           2.1.0(3)     ntoskrnl      
  73.0            USTS   c0000004                                            stall pid                2.2.0                      
  73              RESET                                                                               5.1.0        usbccgp       
  73              ok                                                                                  5.2.0                      
  73.0            CTL    80 06 00 01  00 00 12 00                            GET DESCRIPTOR           6.1.0        ntoskrnl      
  73.0        18  IN     12 01 00 02  ef 02 01 40  83 04 f1 ff  00 01 01 02  .......@........         6.2.0                      
                         03 01                                               ..                       6.2.16                     
  73.0            CTL    80 06 00 02  00 00 09 00                            GET DESCRIPTOR           7.1.0(3)     ntoskrnl      
  73.0            USTS   c0000004                                            stall pid                7.2.0                      
  73              RESET                                                                              10.1.0        usbccgp       
  73              NTSTS  c0000001                                            failed                  10.2.0                      
  73.0            CTL    80 06 00 01  00 00 12 00                            GET DESCRIPTOR          11.1.0        ntoskrnl      
  73.0            USTS   80000300                                            bad parameter           11.2.0                      
  73              RESET                                                                              12.1.0        usbccgp       
  73              NTSTS  c000000e                                            no device               12.2.0                      

### USB中断 / USB Interrupt

是

### 缓存 / Cache

否

### 商业 / Business

- [ ] 是 / Yes

**Comment by sakumisu** [comment]
fsdev 不允许开log，over
