### ISSUE TITLE
关于高速hub接全速设备的拆分传输

### ISSUE THREAD

**Issue by Antecer** [cherry-embedded/CherryUSB#279]
如题，最近在研究这方面的实现。我检索了一下代码仓库，只看到相关功能的头文件定义，但是没找到实现的代码，是还没有做支持吗？

**Comment by sakumisu** [comment]
ehci, xhci是支持的，其余不支持

**Comment by sakumisu** [comment]
dwc2仅支持高速接高速，高速接全速大部分mcu不支持，阉割了寄存器

**Comment by Antecer** [comment]
原来如此，我知道了。
