### ISSUE TITLE
USB-MTP（Media Transfer Protocol）

### ISSUE THREAD

**Issue by HubertXie** [cherry-embedded/CherryUSB#28]
是否考虑增加 MTP？

设备需要通过USB与PC进行文件传输，目前有两种方案
1、使用大容量存储(MSC)
使用MSC需要配合FAT文件系统， 由于FAT没有擦写均衡以及掉电保护，不适合用于设备中。

2、使用MTP
可以兼顾文件系统的性能以及与PC交互的便捷性，目前看一些USB协议栈好像都没支持这种class，不知道是难度太大还是需求太少。

**Comment by sakumisu** [comment]
周末安排上，之前只考虑过主机使用，配合 手机开启 MTP 功能

**Comment by zhangshengping** [comment]
大佬，MTP的设备暂时没有实现是吗？
看了一下代码里面的回调是空的。

**Comment by sakumisu** [comment]
> 大佬，MTP的设备暂时没有实现是吗？ 看了一下代码里面的回调是空的。

没有呢，暂时没有时间更新这么多

**Comment by sakumisu** [comment]
MTP 暂时不做支持了

**Comment by YGDL** [comment]
大佬，MTP设备类哪时候上线啊？太想用了

**Comment by sakumisu** [comment]
> 大佬，MTP设备类哪时候上线啊？太想用了

已经支持，商业收费，不开源
